# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

default: &default
  sendgrid_username: <%= ENV["LUMA_SENDGRID_USERNAME"] %>
  sendgrid_password: <%= ENV["LUMA_SENDGRID_PASSWORD"] %>

development:
  <<: *default
  secret_key_base: f82729db85a0c0e2017fefc51cc0a3ce9673bf66e6c8e7cad0dfb1fbabd1dba73ef51a5a85200d4e07bc7a7807457fc17ba3ce0fb6598b4c95c16f1e9c1d8b76

test:
  <<: *default
  secret_key_base: 252a6bd18bb96479c2a253c6561a42aab66d445c17e89adfc7df71a4eaae34d7fc2bb22efa3c3048c89038eb8f4597324e2cf442502984fb6bec315ffa9b35b2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  <<: *default
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>